### ISSUE TITLE
Start instruktioner

### ISSUE THREAD

**Issue by dv222bk** [jc222fi/Webbramverk#1]
Jag kör Cloud9 så jag vet inte om det har något med det att göra, men för att få igång allt var jag tvungen att skriva "bundle update" istället för "bundle install", annars funkade inte din kod.

**Comment by jc222fi** [comment]
Har ju glömt skriva på varje issue, så du lär väl få typ 18 mail extra ;-)

Jag har inte använt Cloud9, så det hade jag ingen aning om. Fixat till i readme-filen nu.

**Comment by ehamrin** [comment]
Kan inte köra applikationen med de instruktioner som finns. Är inte användare av c9, men om jag följer instruktionerna fungerar det inte.

1. Jag kan inte släppa in en katalog, utan gjorde en ```git glone```, då jag annars måste ladda upp alla filer manuellt.

2. När jag försöker köra `bundle install` eller `bundle update` får jag meddelandet `bash: bundle: command not found`
