### ISSUE TITLE
Kod: before_action

### ISSUE THREAD

**Issue by dv222bk** [jc222fi/Webbramverk#15]
before_action behöver bara skrivas en gång och inte en gång framför varje del i koden som användar sig av den. Den används som standard före alla actions om man inte anger annat. Rekommenderar att du tar en till titt på dokumentationen ang. before_action.

**Comment by jc222fi** [comment]
Fick lite flashback från asp och fick för mig att man var tvungen att skriva allt specifikt för varje action i controllern.
