### ISSUE TITLE
Allmäna åsikter

### ISSUE THREAD

**Issue by dv222bk** [jc222fi/Webbramverk#18]
Kanske är en idé att inkludera funktionalitet så att en användare kan ta bort sitt account samt ändra detaljer som email, användarnamn och lösenord. I riktiga världen så kan man få stora problem om användare inte kan ta bort sig själva från databasen.

Jag ser inte riktigt poängen, just nu, med att inkludera namn och användarnamn till varje användare, då de knappt används. Namn används ganska flitigt i och för sig, men jag gillar inte direkt de platser det används på. Tycker epost eller användarnamn lika gärna hade kunnat användas där istället. Användarnamn kan också skippas om man vill, då epost är en tillräcklig identifierare för användare.

Om jag hade varit du så hade jag ändrat om språket i applikationen till antingen Engelska eller Svenska, då det känns konstigt med den kraftiga blandningen.

Jag gillar hur du har löst generationen av api nycklar, riktigt snyggt! Du har också en bra kodstruktur överlag.

Du har en del att jobba på. Det mesta är små saker dock, så oroa dig inte, det fixar du lätt! :)

**Comment by jc222fi** [comment]
Fixade till de ställen där det hade slunkit med lite svenska, jag föredrar själv att koda på engelska fullt ut men råkade ta med lite svenska när jag tittade på demofilmerna som John spelat in.

Blev lite stressad på slutet, så jag råkade glömma bort en hel del slarvfel. Håller helt med dig att databasen innehåller för mycket onödig information, men den blev nedprioriterad för att hinna klart till deadline.

Bra jobbat med feeback, det var lärorikt :-)

**Comment by 1dv450** [comment]
:+1: Bra feedback och bra att du gått igenom och stängt de issues du fått
