### ISSUE TITLE
"Komma igång med applikationen"-instruktioner

### ISSUE THREAD

**Issue by ehamrin** [jc222fi/Webbramverk#19]
Kan inte köra applikationen med de instruktioner som finns. Är inte användare av c9, men om jag följer instruktionerna fungerar det inte.
1. Jag kan inte släppa in en katalog, utan gjorde en git glone, då jag annars måste ladda upp alla filer manuellt.
2. När jag försöker köra `bundle install` eller `bundle update` får jag meddelandet `bash: bundle: command not found`

**Comment by ehamrin** [comment]
Jag löste det genom att kopiera in en Vagrant maskin som jag kör det mot, men instruktionerna bör testas genom att själv gå igenom stegen från början och skriva ner alla små steg som det innebär

**Comment by ehamrin** [comment]
Det fungerade om jag valde RoR som template och lade in länken till repositoriet och gjorde en clone vid skapandet av workspace, instruktionerna bör uppdateras

**Comment by jc222fi** [comment]
Instruktioner uppdaterade.
