### ISSUE TITLE
Seed

### ISSUE THREAD

**Issue by ehamrin** [jc222fi/Webbramverk#20]
Det genereras en nyckel i seed-filen. Denna bör dock hårdkodas här för att undvika onödigt jobb för testare. Jag var tvungen att kopiera in denna nyckel i alla anrop. Hade den varit hårdkodat här, med samma värden i postman-filen hade detta steg undvikits

**Comment by jc222fi** [comment]
Jag är lite osäker på hur jag skulle kunna hårdkoda in en nyckel, när jag försöker tilldela fältet en hårdkodad nyckel slumpas den ändå. Antar att det har att göra med att jag har before_create: generate_key på min klass så den skapas innan själva objektet skapas.

**Comment by ehamrin** [comment]
I seeds borde det gå att göra något liknande 

``` ruby
key = ApiKey.create(:app_name => "coola appen") #Här borde nyckeln sparas med ett slumpat värde eftersom att du kör create
key.user = u1 #Här tilldelar du en user till nyckeln redan
key.key = "6be9f36e7928df8a58aadwfse98e90de" #Nyckeln är redan sparad, så nu sätter vi dit ett nytt värde som vi vet om
key.save #Spara den på nytt
```

Jag hoppas att det borde kunna funka då `before_create` enligt [denna sida](http://apidock.com/rails/ActiveRecord/Callbacks/before_create) endast körs om modellen inte tidigare är sparad. Har tyvärr inte möjlighet att testköra själv idag

**Comment by jc222fi** [comment]
Det funkade alldeles utmärkt, tack!
