### ISSUE TITLE
Github auth

### ISSUE THREAD

**Issue by ehamrin** [jc222fi/Webbramverk#21]
När jag besöker länken `https:/[Mitt Workspace].c9users.io/auth/github` skickas jag till `https://ettdvfyrahundrafemtio-api-jc222fi.c9users.io/auth/github?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=51a4a965cce287c48845a5c6462735ea18b58cf624b9b603`

Vi får olika länkar till våra applikationer och därför fungerar inte din verifiering då Github kommer att skicka användaren till ditt workspace

**Comment by jc222fi** [comment]
Det är helt logiskt när du skriver det att det blir en uri mismatch, jag tänkte inte riktigt så långt. Jag hade den live ett tag för att jag fick problem ruby och windows under arbetet med oauth, men när jag testade att göra via Cloud9 behövde jag inte starta om servern efter varje ändring för att testa, och reflekterade då inte över hur det kunde påverka redirecten.
