### ISSUE TITLE
Skapa användare: Felrapportering

### ISSUE THREAD

**Issue by dv222bk** [jc222fi/Webbramverk#3]
Så fort ett fel inträffar i skapa användare vyn visas minst två felmeddelanden för användaren, där minst två av dom också betyder samma sak. Dessutom visas felmeddelande arrayen. Se bild [här](http://puu.sh/n0C4t.png)

**Comment by jc222fi** [comment]
Denna kommentar gäller egentligen alla fixade felmeddelanden, hade råkat använda <%= istället för bara <% i mina foreach loopar, så den skrev ut allt först en och en, sedan hela arrayen.
