### ISSUE TITLE
Skapa användare: Routing

### ISSUE THREAD

**Issue by dv222bk** [jc222fi/Webbramverk#5]
När man skapar en användare är det tänkt att användaren ska bli inloggad och skickas till "inloggningssidan". Det här sker dock inte då ett routing fel inträffar. Se bild [här](http://puu.sh/n0Cic.png)

Användaren skapas dock och går att logga in med.

**Comment by jc222fi** [comment]
En miss i controllern med vart jag redirectar, fixat till så att den pekar på rätt path.
