### ISSUE TITLE
Api Keys Routing

### ISSUE THREAD

**Issue by dv222bk** [jc222fi/Webbramverk#9]
Känns konstigt att listan med api nycklar för varje användare ligger under /keys, men när man skapar en ny nyckel hamnar man i /api_keys/new.

Antingen /keys eller /api_keys borde användas här.

**Comment by jc222fi** [comment]
Jag tyckte det var meckigt med routing, hade problemet att den klagade på att det redan fanns när jag försökte använda /api_keys/show och /api_keys/new. Läste på lite mer på området och ändrade show till index, så blev det inte längre någon konflikt.
